### ISSUE TITLE
Add favicons

### ISSUE THREAD

**Issue by webknjaz** [douhack/douhack#35]
plz integrate typical favicons and apple-flavoured pictures
I asked @Suzzy to create corresponding images http://rghost.ru/private/8mcBqJ8GH/b423dc31887cc4dc2d118a14c6183bc7
https://psv4.vk.me/c609431/u8056787/docs/9e60ee69a966/64x64.png?extra=tOJW2qRhLuuGZVi13NdAKIzDuf4XpDtMKbS8DMccn3VYaxm1N4os8HQRcnfwrdEWS7hOyJLlCIo6_QnoqpN2aFc3xg2YEw

**Comment by Kiwka** [comment]
Files are not avaialable through both links

**Comment by Suzzy** [comment]
http://rghost.ru/private/8ynbvWL9v/88343b52c89d6db03f48705847d3345f

2015-02-10 23:10 GMT+02:00 Olena Sovyn <notifications@github.com>:

**Comment by Kiwka** [comment]
скачала. дякую!
